import React from 'react';
import { convertFromRaw, EditorState } from "draft-js";



const ExportToHTML = ({ data, config }) => {

    function DraftjsConversion(msg) {
        return EditorState
            .createWithContent(convertFromRaw(JSON.parse(msg)))
            .getCurrentContent()
            .getPlainText()
    }

    console.log('exprtHTML')

    return (
        <>
            {Object.keys(data).map((folder) => (
                <div
                    key={folder}
                    style={{
                        backgroundColor: config.primary,
                        fontFamily: 'Source Sans Pro, Arial, sans-serif',
                        margin: '2%',
                        borderRadius: '20px',
                    }}
                >
                    <h1
                        style={{
                            margin: '0',
                            padding: '1% 2%'
                        }}>
                        {folder}
                    </h1>
                    {data[folder].map(item => (
                        <div
                            key={item.key}
                            style={{
                                padding: '0',
                                borderBottom: `3.5px solid white`
                            }}
                        >
                            <div style={{
                                margin: '2%'
                            }}>
                                <div style={{ marginBottom: '1%' }}>
                                    {item.currentDate}
                                </div>
                                <a
                                    href={item.url}
                                    style={{
                                        textDecoration: 'none',
                                        color: config.quaternary,
                                    }}>
                                    {item.url}
                                </a>
                                <p>{DraftjsConversion(item.msg)}</p>
                            </div>


                            <ul style={{
                                padding: '0 3%',
                                margin: '0 2%'
                            }}>
                                {item.comment.map(comm => (
                                    <li
                                        key={comm.key}
                                        style={{
                                            borderLeft: `4px solid ${config.main}`,
                                            listStyle: 'none',
                                            marginBottom: '2%',
                                            padding: '0 2%'
                                        }}>
                                        <div
                                            style={{ marginBottom: '2%' }}>
                                            {comm.currentDate}
                                        </div>
                                        <p
                                            style={{
                                                padding: '0 2%',
                                                margin: '0'
                                            }}>
                                            {DraftjsConversion(comm.msg)}
                                        </p>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    ))}
                </div>
            ))}
            <div
                style={{
                    fontSize: '1.3em',
                    fontFamily: 'Source Sans Pro, Arial, sans-serif',
                }}>
                Generated by Juuten
            </div>
        </>
    )
}

export default ExportToHTML
